### ISSUE TITLE
Anti pattern followed in the files in  lib/

### ISSUE THREAD

**Issue by JAYKRISHNAN** [prasanth94/Amortization-schedule#3]
For more details visit : http://blog.codeclimate.com/blog/2012/02/07/what-code-goes-in-the-lib-directory/

**Comment by prasanth94** [comment]
I have fixed this issue in the commit - https://github.com/prasanth94/Amortization-schedule/commit/bc7c7ac6fdd8fcb815c1f7fa57684b5307988d40

Let me know if further improvements are required.

**Comment by JAYKRISHNAN** [comment]
This looks good 👍
