### ISSUE TITLE
Improve the readability of the modules in lib/

### ISSUE THREAD

**Issue by JAYKRISHNAN** [prasanth94/Amortization-schedule#5]

**Comment by prasanth94** [comment]
I have improved the readability of the lib/ files and fixed this issue in the following commits:
https://github.com/prasanth94/Amortization-schedule/commit/9c6e6010778138451b1e5814ab6756e460870b14
https://github.com/prasanth94/Amortization-schedule/commit/0a48d5bbc4c4c2fb2630a7c355c33ea5a389d963

**Comment by JAYKRISHNAN** [comment]
Looks good!
