### ISSUE TITLE
Specs are not sufficient to test the respective methods

### ISSUE THREAD

**Issue by m-arav** [prasanth94/Amortization-schedule#6]
These [specs](https://github.com/prasanth94/Amortization-schedule/blob/08c7c20d1cd6265aef2205284918595318565b6f/spec/models/loan_spec.rb#L44-L52) only test if the such a method call will be received, thus the spec does not describe anything about the method itself. Try writing more specs to test more aspects of the method concerned.

**Comment by prasanth94** [comment]
I have improved my specs in this commit - https://github.com/prasanth94/Amortization-schedule/commit/c741ca5479e919ec44be122d155db7e0a61f71e4
 
You can go through it and let me know if something else is missing.

**Comment by m-arav** [comment]
Good improvements to the specs
